# YAML settings for the app
local: &DEFAULT !AppConfig
  work_dir: /Users/hxiao/Documents/tf-best-practice/
  data_dir: data/
  log_dir: log/
  script_dir: script/
  data_file: data/*/db.json.2017-*-*.gz
  parameter_file: settings/parameter.yaml
  parameter_profile: default
  log_format: '%(asctime)s:%(filename)s:%(funcName)s:[%(levelname)s] %(message)s'

debug: !AppConfig
  <<: *DEFAULT
  parameter_profile: lstm_large

deploy: !AppConfig
  <<: *DEFAULT
  work_dir: /opt/workspace/
  parameter_profile: default


