# YAML settings for the model parameters
default: &DEFAULT
  batch_size: 32
  split_ratio: 0.6
  train_embedding: true
  cell: lstm
  init_state_type: var
  dilation: [1, 2, 4, 8, 16, 32]
  num_hidden: 64
  metric: cosine
  num_epoch: 1000
  optimizer: rmsp
  learning_rate: 1.0e-4
  decay_rate: 0.97
  loss: logisitc
  len_threshold: 200
  loss_at_each_step: true
  num_eval: 100
  eval_step: 1000
  infer_seq_length: 100
  infer_batch_size: 10
  dim_embed: 16

lstm: &LSTM
  <<: *DEFAULT
  cell: lstm
  len_threshold: 100
  batch_size: 512
  num_eval: 1000
  dim_embed: 128
  num_hidden: 128
  num_epoch: 100
  infer_seq_length: 100
  num_eval: 1000

sru:
  <<: *LSTM
  cell: sru
